version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ai-database
    environment:
      POSTGRES_DB: ai-data
      POSTGRES_USER: bwibow
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:


networks:
  mynetwork:
